### ISSUE TITLE
FDroid

### ISSUE THREAD

**Issue by C0R10L4NU2** [redfish64/TinyTravelTracker#1]
Thank you for your hard work on this project. 
It would be really cool to have this in the F-Droid-Repo.

Several users there have already asked for it to be included [here](https://f-droid.org/forums/topic/tiny-travel-tracker/), but the admins could not build the dependencies outright.

**Comment by redfish64** [comment]
Cool, I'm glad people like it! I'll try to get it into a format that F-Droid accepts.

**Comment by redfish64** [comment]
I fixed the problems they described and created a merge request for it. Thanks for bringing this to my attention.
