### ISSUE TITLE
Wrong float representation on GPX export

### ISSUE THREAD

**Issue by sashw** [redfish64/TinyTravelTracker#4]
When I export the tracked GPS data to a GPX file, all the float values use a comma instead of a dot as a decimal mark (lat="1,2345" lon="4,5678" as well as elevation). This way the GPS locations aren't recognized correctly when using them somewhere else. 

I'm using CM11 with the language set to german. I don't know if this affects the output.

**Comment by redfish64** [comment]
I fixed this. Will be in version 1.0.13

**Comment by redfish64** [comment]
You can follow the merge request here:

https://gitlab.com/fdroid/fdroiddata/merge_requests/1017

Unfortunately, it seems there are some problems getting it pushed through.

**Comment by sashw** [comment]
Thanks for the fix. I appreciate your effort.

**Comment by sashw** [comment]
Works as expected. Thanks!
