### ISSUE TITLE
Request: some way to donate/support TTT

### ISSUE THREAD

**Issue by ianmcorvidae** [redfish64/TinyTravelTracker#40]
I'm using TTT from f-droid in part because I don't want ads, but I'm getting a lot of value and use out of it, so I'd like to help support its development some way. I know that f-droid supports listing donation URLs as well, plus some specific subcategories: https://f-droid.org/manual/fdroid.html#Donate

Is there somewhere that can be listed here in the README, on f-droid, wherever else is appropriate?

**Comment by redfish64** [comment]
I added a bitcoin donation address and a patreon link to the README. Thanks for your support; not necessary, but appreciated!

**Comment by redfish64** [comment]
Closing as fixed.
