### ISSUE TITLE
[Bug] App crashes when pressing 'back' on launch

### ISSUE THREAD

**Issue by collectorgeneral** [redfish64/TinyTravelTracker#43]
Say you accidentally open the app, before the map is displayed, if you press the 'back' softkey or button, the app seems to crash. However, the notification shows it is active. This seems to be quite reproducible. This behaviour appears to not happen once the map and everything else is initialised. 

Attached a logcat for your reference.

App details:
App version installed: V 1.1.10; Source: F-droid.
Phone details:
Oneplus One (aka A0001 aka Bacon) running Cyanogen OS 13.1.2 (Android 6.0.1). 
[20160825_TTT_log_2.txt](https://github.com/redfish64/TinyTravelTracker/files/438120/20160825_TTT_log_2.txt)

Update:
As of Version 1.1.14, this does not seem to occur. I will keep an eye out for it, if it occurs again I will update here. You can close the issue if you want to.

**Comment by redfish64** [comment]
Thanks. I noticed something like this while working on some other things and fixed it, prior to 1.1.14. Feel free to reopen if it reoccurs.
