### ISSUE TITLE
Issue: No map displayed

### ISSUE THREAD

**Issue by Rudertier** [redfish64/TinyTravelTracker#62]
Since I had to install TTT on a new phone, the maps are no longer displayed. I'm using the Fdroid version on a nougat phone. I really enjoy the app and hope the issue can be fixed. Please let me know if you need any further information. 
Cheers

**Comment by redfish64** [comment]
Yea, I'm aware of this. The Mapzen map server is no longer compatible with the version of tangram I use. I fixed my code, but there seems to be a unix permissions problem on the f-droid server, so it won't build. I opened a ticket, but there is little progress:  https://gitlab.com/fdroid/fdroidserver/issues/268

You can either install from google play, or wait until it gets fixed. If you really want, I can put the apk up here under releases and you can "side-load" it.

**Comment by redfish64** [comment]
I uploaded it here: https://github.com/redfish64/TinyTravelTracker/releases/tag/v1.1.27

**Comment by Rudertier** [comment]
Hey,
Thanks a lot. I'm glad to hear that work is ongoing. 
Cheers

**Comment by jgronefe** [comment]
Hi,
I got the new build from FDroid. Maps work! 
Thanks a lot!
