### ISSUE TITLE
Add donation option (bitcoin?)

### ISSUE THREAD

**Issue by PrzemoF** [redfish64/TinyTravelTracker#65]
Please add a donation option, preferably bitcoin.

**Comment by satlink** [comment]
Donations:

Bitcoin: 19bit8J9VFY9DMGbcYNrH4PzkUPdS8Rx1f

Patreon: https://www.patreon.com/redfish64

**Comment by PrzemoF** [comment]
W dniu 2017-04-19 11:12, satlink napisał(a):

> Donations:
> 
> Bitcoin: 19bit8J9VFY9DMGbcYNrH4PzkUPdS8Rx1f
> 
> Patreon: https://www.patreon.com/redfish64
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Thanks for making a great piece of software! Some small sum of bitcoin 
transferred :-)

Regards,
Przemo
