### ISSUE TITLE
Town/city names not showing.

### ISSUE THREAD

**Issue by EgrettaGarzetta** [redfish64/TinyTravelTracker#84]
Having to guess or even import the data to other apps to find out where I've been.

**Comment by redfish64** [comment]
I had this problem myself, but for Chinese fonts. Just updated the tangram version the app uses for maps, and it fixed my issue. It's in 1.1.43 and should be available in a couple of days. You can monitor the build here:

https://f-droid.org/wiki/index.php?title=com.rareventure.gps2/lastbuild&redirect=no

It will be build 86.

**Comment by EgrettaGarzetta** [comment]
Not an issue for me on 1.1.45, not sure when but definitely fixed.
