### ISSUE TITLE
How to stop app and notification?

### ISSUE THREAD

**Issue by licaon-kter** [redfish64/TinyTravelTracker#9]
1.0.13 from F-Droid on 5.1.1

I can kill the app say via back _button to kill foreground app_ but the notification stays there.
I can get the notification from a _green frog that can't be disabled_ to a _red one that can be_ by toggling location services on/off but that's not a sure way, it does not work *all* the time.
The application does not show up as an running app in the app list, in the app info the force stop button is grayed out, what I can do is to uncheck show notifications (it will dissappear) and recheck it back an it won't appear.

Can we get an _"Exit app"_ menu item?

**Comment by redfish64** [comment]
If you unclick "Collect GPS Data" in the settings screen, the green frog will go away. It's presence indicates that TTT is collecting GPS points.

If you turn off Collect GPS Data, the app is effectively shut down.

**Comment by licaon-kter** [comment]
Umm, ok, makes sense, although force close should you know... close it.

Yes I can uncheck that, but since https://github.com/redfish64/TinyTravelTracker/issues/8 happens it's kinda cumberstone.

**Comment by licaon-kter** [comment]
Closing this for now.
