### ISSUE TITLE
App slows down and eventually hangs phone in map view

### ISSUE THREAD

**Issue by maciozo** [redfish64/TinyTravelTracker#90]
I recently installed LineageOS 16.0 on my LG V20 (H990DS). I imported the GPX file I exported previously, but when I try to view the map, the phone quickly slows down to a crawl, and then hangs, forcing a hard reboot. No points get displayed either.

I'm using TTT 1.1.43 from F-Droid.

I have managed to work around it by quickly zooming in and swiping the timescale all the way in and to the beginning.

**Comment by redfish64** [comment]
Did you try changing the map style?

Does the problem only occur after you've imported your old points, or does
it even occur without any points added?

maciozo <notifications@github.com> 於 2019年5月8日 週三 01:36 寫道：

**Comment by maciozo** [comment]
@redfish64 
I actually can't reproduce the problem anymore, even after clearing all the app data. Perhaps it's only an issue on completely fresh ROM installs.

**Comment by redfish64** [comment]
Glad it worked out for you.  Let me know if it reoccurs or you can find out
more about it.

maciozo <notifications@github.com> 於 2019年5月10日 週五 01:10 寫道：

**Comment by maciozo** [comment]
Cheers, I'll close the issue for now.
